Comicteca/force-app/main/default/objects/Editorial__c/Editorial__c.object-meta.xml
<CustomObject>
    <label>Editorial</label>
    <nameField>
        <label>Nombre de Editorial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Editoriales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Comicteca/force-app/main/default/objects/Libro__c/Libro__c.object-meta.xml
<CustomObject>
    <label>Libro</label>
    <nameField>
        <label>Nombre de Libro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Libros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Comicteca/force-app/main/default/objects/Libro__c/fields/Ano_de_publicacion__c.field-meta.xml
<CustomField>
    <fullName>Ano_de_publicacion__c</fullName>
    <label>Año de Publicación</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Comicteca/force-app/main/default/objects/Libro__c/fields/Editorial__c.field-meta.xml
<CustomField>
    <fullName>Editorial__c</fullName>
    <label>Editorial</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Comicteca/force-app/main/default/objects/Libro__c/fields/Numero_de_paginas__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_paginas__c</fullName>
    <label>Número de páginas</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Comicteca/force-app/main/default/classes/BookListController.cls
public inherited sharing class BookListController {
    @AuraEnabled
    public static List<Libro__c> getList(){
        try {
        List<Libro__c> books = [SELECT Id, Name, Numero_de_paginas__c, Editorial__c, Ano_de_publicacion__c FROM Libro__c ORDER BY Name];
             return books;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static void getData(String nom, Decimal num_pag, String editorial, Decimal ano){
        try {
        Libro__c newLibro = new Libro__c();
             newLibro.Name = nom;
             newLibro.Numero_de_paginas__C = num_pag;
             newLibro.Editorial__c = editorial;
             newLibro.Ano_de_publicacion__c = ano;
             insert newLibro;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void getBookToRemove(String idBook){
        try {
        Libro__c book = [SELECT Id, Name, Numero_de_paginas__c, Editorial__c, Ano_de_publicacion__c FROM Libro__c WHERE id = :idBook];
            delete book;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}